Component = Sentinel
Component.PreferredJavaVersion = 8
Component.InstallerVersion = 4.9.0
Component.LongName = Axway Sentinel Server
Component.PassPortAMApi = Mixed
Component.TomcatUsed = true
Component.SupportedOS = aix-power-32;aix-power-64;sun-sparc-64;sun-x86-64;hpux-ia64;linux-x86-32;linux-x86-64;win-x86-32;win-x86-64;linux-s390-64
Component.SoftDependencies = PassPort;Synchrony_Database
Component.LimitedCluster = NoCluster
Component.Implementation = Java
Component.Version = 4.2.0
Component.SupportedAccessManagers = Sentinel;PassPortAM;RSA
Component.SourceDiskNumber = 1
Component.UsePassPortSSO = true
Component.Parent = Axway_Installer
Component.UseSelfRegistration = PP44
Component.FileIdent = SNT
Component.ComponentType = ComponentPack
Component.JavaHome = /opt/monitoring_oracle/Java/linux-x86/jre8_u40_64


DashboardServer = false
DashboardServer.Type = Module
DashboardServer.Title = Dashboard Server
DashboardServer.ParentName = SentinelServer
DashboardServer.ModuleType = NotInstalled
DashboardServer.LogicalName = DashboardServer


CreationDate = 01-01-2008
CreationDate.Type = Date
CreationDate.Format = dd-MM-yyyy


PassPortSSOPort = 
PassPortSSOPort.Type = Integer
PassPortSSOPort.Min = 1024
PassPortSSOPort.DefaultValue = 1311
PassPortSSOPort.Max = 65535


IntegrationDir = Sentinel_V4.2.0
IntegrationDir.Type = Directory


SentinelWebMonitoring = false
SentinelWebMonitoring.Type = Module
SentinelWebMonitoring.ModuleType = NotInstalled
SentinelWebMonitoring.LogicalName = SentinelWebMonitoring
SentinelWebMonitoring.Title = Web Monitoring
SentinelWebMonitoring.ParentName = Sentinel_V4.2.0


WindowsServiceDescription = 
WindowsServiceDescription.DefaultValue = Axway Sentinel is an end-to-end business, system and technical event monitoring tool.


ProbeServer = false
ProbeServer.Type = Module
ProbeServer.ParentName = Sentinel_V4.2.0
ProbeServer.ModuleType = NotInstalled
ProbeServer.LogicalName = ProbeServer
ProbeServer.Title = Probe Server


bundledDependencyForStandard = true


AuditAccInt = false
AuditAccInt.Type = Module
AuditAccInt.ParentName = SentinelServer
AuditAccInt.ModuleType = NotInstalled
AuditAccInt.LogicalName = AuditAccInt
AuditAccInt.Title = Monitoring for Accounting Integrator


SelectedBitArchitecture = 64


InstMode = Install


JettyHostName = sentinel


Sentinel_V4.2.0 = true
Sentinel_V4.2.0.Type = Module
Sentinel_V4.2.0.ModuleType = Installed
Sentinel_V4.2.0.LogicalName = Sentinel_V4.2.0
Sentinel_V4.2.0.ParentName = null
Sentinel_V4.2.0.Title = Axway Sentinel Server V4.2.0


CommonMain = true
CommonMain.Type = Module
CommonMain.ModuleType = Installed
CommonMain.LogicalName = CommonMain
CommonMain.ParentName = Sentinel_V4.2.0
CommonMain.Title = Common Settings


Database = true
Database.Type = Module
Database.ModuleType = Installed
Database.LogicalName = Database
Database.ParentName = Sentinel_V4.2.0
Database.Title = Database


SentinelServer = true
SentinelServer.Type = Module
SentinelServer.ModuleType = Installed
SentinelServer.LogicalName = SentinelServer
SentinelServer.ParentName = Sentinel_V4.2.0
SentinelServer.Title = Sentinel Server


AccessManagerConfiguration = true
AccessManagerConfiguration.Type = Module
AccessManagerConfiguration.ModuleType = Installed
AccessManagerConfiguration.LogicalName = AccessManagerConfiguration
AccessManagerConfiguration.ParentName = SentinelServer
AccessManagerConfiguration.Title = Access Manager


CorrelationServer = true
CorrelationServer.Type = Module
CorrelationServer.ModuleType = Installed
CorrelationServer.LogicalName = CorrelationServer
CorrelationServer.ParentName = SentinelServer
CorrelationServer.Title = Correlation Server


NewWebDashboard = true
NewWebDashboard.Type = Module
NewWebDashboard.ModuleType = Installed
NewWebDashboard.LogicalName = NewWebDashboard
NewWebDashboard.ParentName = Sentinel_V4.2.0
NewWebDashboard.Title = New Web Dashboard


InstallDir = /opt/monitoring_oracle/Sentinel/


InstallationType = Custom


CommonMainInst = true


SentinelServerInst = true


AccessManagerConfigurationInst = true


CorrelationServerInst = true


DatabaseInst = true


ServerName = sentinel


ProductKey = 8IAFWAGIA45DS2NT5NQM4RKZ2


JettyDir = /opt/monitoring_oracle/Sentinel/jetty


RMIListener = 1308
RMIListener.Type = IPPortOwner
RMIListener.Max = 65535
RMIListener.Min = 1024


TelnetListener = 1310
TelnetListener.Type = IPPortOwner
TelnetListener.Max = 65535
TelnetListener.Min = 1024


TelnetRemoteAccess = true


MainAccessPort = 1309
MainAccessPort.Type = IPPortOwner
MainAccessPort.Max = 65535
MainAccessPort.Min = 1024


JettyCommandPort = 8055
JettyCommandPort.Type = IPPortOwner
JettyCommandPort.Max = 65535
JettyCommandPort.Min = 1024


JettySSOEnabled = true


JettySSOPort = 8099
JettySSOPort.Type = IPPortOwner
JettySSOPort.Max = 65535
JettySSOPort.Min = 1024


CommonKeystoreFile = /opt/monitoring_oracle/Sentinel/conf/security/keystore.jks


CommonKeystorePass = u9jkVm/WHFn+OZyQILRJNQ==
CommonKeystorePass.Format = AES128


CommonTruststoreFile = /opt/monitoring_oracle/Sentinel/conf/security/truststoreSSO.jks


CommonTruststorePass = u9jkVm/WHFn+OZyQILRJNQ==
CommonTruststorePass.Format = AES128


PassPortTruststoreFile = /opt/monitoring_oracle/Sentinel/conf/security/truststorePassPort.jks


PassPortTruststorePass = u9jkVm/WHFn+OZyQILRJNQ==
PassPortTruststorePass.Format = AES128


SSLConf = true


ProtocolVersion = TLSv1.2


KeystoreType = JKS


KeystoreFilename = /opt/monitoring_oracle/Sentinel/conf/security/keystore.jks
KeystoreFilename.Type = File


KeystorePassword = u9jkVm/WHFn+OZyQILRJNQ==
KeystorePassword.Format = AES128


KeystorePasswordConfirm = u9jkVm/WHFn+OZyQILRJNQ==
KeystorePasswordConfirm.Format = AES128


KeystorePasswordServer = u9jkVm/WHFn+OZyQILRJNQ==
KeystorePasswordServer.Format = AES128


KeystorePasswordServerConfirm = u9jkVm/WHFn+OZyQILRJNQ==
KeystorePasswordServerConfirm.Format = AES128


TruststoreType = JKS


TruststoreFilename = /opt/monitoring_oracle/Sentinel/conf/security/truststoreSSO.jks
TruststoreFilename.Type = File


TruststorePassword = u9jkVm/WHFn+OZyQILRJNQ==
TruststorePassword.Format = AES128


TruststorePasswordConfirm = u9jkVm/WHFn+OZyQILRJNQ==
TruststorePasswordConfirm.Format = AES128


PassPortAMDomain = Synchrony


PassPortAMCompIdentifier = default


UseSSL = true


PassPortAMCertificatePath = /opt/monitoring_oracle/Sentinel/conf/security/keystore.jks


PassPortAMCertificatePassword = axway*


USE_SECURE_DATABASE_CONNECTION = false


TRUSTSTORE_PATH = 


TRUSTSTORE_TYPE = JKS


TRUSTSTORE_PASS = t29TjOf+lRtuaYOy99jG7A==
TRUSTSTORE_PASS.Format = AES128


TRUSTSTORE_PASS_CONFIRM = t29TjOf+lRtuaYOy99jG7A==
TRUSTSTORE_PASS_CONFIRM.Format = AES128


DB_SSL_PORT = 


XIP_SEP = /


DB_TYPE = Oracle11


DB_CREATE_ACTION = SCHEMA


DB_URL_TYPE = BasicURL


CHECK_INFORMATION = true


USE_A_NOT_ASSISTED_URL = false


id = 0


DB_NAME = FREE


DB_SERVICE_NAME = 


DB_HOST = sentinel


DB_PORT = 11521


DB_ADMIN_LOGIN = SYSTEM


DB_ADMIN_PASSWORD = rG84YSsY2RD5DU8DbLkklw==
DB_ADMIN_PASSWORD.Format = AES128


SNTL_DATA_WORK = SNTL_DATA_WORK


SNTL_INDEX_WORK = SNTL_INDX_WORK


SNTL_DICO_WORK = SNTL_DICO_WORK


DB_USER = SYSTEM


DB_PWD = rG84YSsY2RD5DU8DbLkklw==
DB_PWD.Format = AES128


DB_ADMIN_URL = jdbc:oracle:thin:@sentinel:11521:FREE


DB_URL = jdbc:oracle:thin:@sentinel:11521:FREE


DB_STANDARD_URL = jdbc:oracle:thin:@sentinel:11521:FREE


DB_STANDARD_USER = SYSTEM


DB_STANDARD_PWD = rG84YSsY2RD5DU8DbLkklw==
DB_STANDARD_PWD.Format = AES128


DB_SCHEMA = SYSTEM


TABLES = 


DB_SCRIPTS = COPY_LAUNCH


FrontEndHttpXmlActivate = true


FrontEndHttpXmlPort = 1301
FrontEndHttpXmlPort.Type = IPPortOwner
FrontEndHttpXmlPort.Max = 65535
FrontEndHttpXmlPort.Min = 1024


FrontEndQltXntfActivate = true


FrontEndQltXntfPort = 1302
FrontEndQltXntfPort.Type = IPPortOwner
FrontEndQltXntfPort.Max = 65535
FrontEndQltXntfPort.Min = 1024


FrontEndQltXmlActivate = true


FrontEndQltXmlPort = 1303
FrontEndQltXmlPort.Type = IPPortOwner
FrontEndQltXmlPort.Max = 65535
FrontEndQltXmlPort.Min = 1024


FrontEndHttpXntfActivate = true


FrontEndHttpXntfPort = 1304
FrontEndHttpXntfPort.Type = IPPortOwner
FrontEndHttpXntfPort.Max = 65535
FrontEndHttpXntfPort.Min = 1024


FrontEndAutoActivate = true


FrontEndAutoPort = 1305
FrontEndAutoPort.Type = IPPortOwner
FrontEndAutoPort.Max = 65535
FrontEndAutoPort.Min = 1024


FrontEndAutoUtfActivate = true


FrontEndAutoUtfPort = 1306
FrontEndAutoUtfPort.Type = IPPortOwner
FrontEndAutoUtfPort.Max = 65535
FrontEndAutoUtfPort.Min = 1024


TrackedEventCapacity = 450
TrackedEventCapacity.Type = Integer
TrackedEventCapacity.Min = 200
TrackedEventCapacity.Max = 2000


AlertByMail = true


FrontEndMailFrom = sender_addr@mycompany.com


FrontEndMailTo = receiver_addr@mycompany.com


FrontEndSmtpHost = smtp.mycompany.com


FrontEndSmtpPort = 25
FrontEndSmtpPort.Type = Integer
FrontEndSmtpPort.Min = 0
FrontEndSmtpPort.Max = 65535


FrontEndAuthenticatedEmails = false


FrontEndSmtpUsername = 


FrontEndSmtpPassword = t29TjOf+lRtuaYOy99jG7A==
FrontEndSmtpPassword.Format = AES128


RMIPortSelection = Automatic


FirstValue = 1350


NatHostActiv = false


NatHost = 


NetworkAdaptersActiv = false


ClientNetworkAdapter = 


FrontEndNetworkAdapter = 


AccessManager = Sentinel


WD_SERVER_USE1 = WD_internal_server


WD_DeployDir = /opt/monitoring_oracle/Sentinel/jetty/webapps/


WD_HostAddress = sentinel


WD_HTTPPort = 8080


WD_HTTPSPort = 8443


WD_HTTPSMutualPort = 8099


WD_SessionTimeout = 900
WD_SessionTimeout.Type = Integer


WD_SERVER_USE = WD_internal_server


WD_USE_SECURE_DATABASE_CONNECTION = false


WD_TRUSTSTORE_PATH = 


WD_TRUSTSTORE_TYPE = JKS


WD_TRUSTSTORE_PASS = t29TjOf+lRtuaYOy99jG7A==
WD_TRUSTSTORE_PASS.Format = AES128


WD_TRUSTSTORE_PASS_CONFIRM = t29TjOf+lRtuaYOy99jG7A==
WD_TRUSTSTORE_PASS_CONFIRM.Format = AES128


WD_DB_SSL_PORT = 



WD_DB_USE = no


WD_DB_USE_EXTERNAL = WD_OracleDB


WD_DB_CHECK_INFORMATION = true


WD_USE_A_NOT_ASSISTED_URL = false


WD_DB_SID_ORA = FREE


WD_DB_NAME_ORA = sentinel


WD_DB_PORT_ORA = 21521


WD_DB_CU_ORA = SYSTEM


WD_DB_CP_ORA = rG84YSsY2RD5DU8DbLkklw==
WD_DB_CP_ORA.Format = AES128


WD_DB_PORT = 21521


WD_DB_NAME = sentinel


WD_DB_SID = FREE


WD_DB_CU = SYSTEM


WD_DB_CP = rG84YSsY2RD5DU8DbLkklw==
WD_DB_CP.Format = AES128


